### ISSUE TITLE
[FR] reflow PDF

### ISSUE THREAD

**Issue by ildar** [SufficientlySecure/document-viewer#253] opened 2017-06-08 18:57 UTC
muPdf capable of reflowing text but it's not e-book Reading app. I think making up this feature + quick switch to "original" mode would make a very good PDF reading app

**Comment by ericwa** [comment] 2017-06-09 22:44
Closing as duplicate of https://github.com/SufficientlySecure/document-viewer/issues/127
Agree this would be nice.

**Closed by ericwa** 2017-06-09 22:44 UTC
