### ISSUE TITLE
Scrolling abruptly stops when auto crop is active

### ISSUE THREAD

**Issue by snelltheta** [SufficientlySecure/document-viewer#89] opened 2015-04-19 03:56 UTC
I should note that the auto cropping of pages is enabled. If I try to scroll fast, it will scroll for a moment then stops abruptly.

**Comment by tuxor1337** [comment] 2015-04-19 07:00
It's only when auto cropping is enabled and it appears for all file types (so it's not related with the most recents update to MuPdf). Yes, it's definitely a bug.

**Comment by tuxor1337** [comment] 2015-04-19 07:19
Might be related to this commit: https://github.com/sufficientlysecure/document-viewer/commit/542ed8ec2c0670256284d01fa4433f69a10237da

**Comment by snelltheta** [comment] 2015-09-08 06:37
Version 2.7.3 doesn't have this issue any further, I believe. Can you confirm?

**Comment by tuxor1337** [comment] 2015-09-08 07:38
This is still the case for the latest version. Please note that the problem only occurs when auto cropping of page margins is activated.

**Comment by ericwa** [comment] 2015-11-02 21:38
I think this might be the cause:
https://github.com/SufficientlySecure/document-viewer/blob/master/document-viewer/src/main/java/org/ebookdroid/core/DecodeServiceBase.java#L301

Why is the calculateRootCropping() method in DecodeServiceBase calling viewState.ctrl.goToPage()? Seems hacky for the page rendering code to generate a "goto page" UI action. I tried commenting that block:
```
        task.node.page.base.runOnUiThread(new Runnable() {

            @Override
            public void run() {
                viewState.ctrl.goToPage(currentPage.viewIndex, offsetX, offsetY);
            }
        });
```
and it fixed this issue (flings stop abruptly when auto cropping is enabled). I can't see any negative side effects of removing that so far.

**Comment by tuxor1337** [comment] 2015-11-02 22:10
Great work! But we have to do some more testing, before we effectively change parts of the code that we don't understand ;-)

I'm shocked once again by the messiness of this code. There are so many hacky details hidden everywhere. In many cases this is due to backwards compatibility. But the more I scan through the code, I feel like a complete rewrite would be the only solution...

**Comment by ericwa** [comment] 2016-05-30 20:09
This seems to be fixed now with https://github.com/SufficientlySecure/document-viewer/pull/157 merged

**Closed by ericwa** 2016-05-30 20:09 UTC
Labels: bug
