### ISSUE TITLE
problem with djvu

### ISSUE THREAD

**Issue by freeco** [sufficientlysecure/document-viewer#66] opened 2015-02-18 21:03 UTC
I can't read this book http://rutracker.org/forum/viewtopic.php?t=4774400
Phone: ThL W3+
Android 4.0.4
Other program on Android have problem to.

DjView 4.9 on Debian work well.

Sorry for my poor English.

**Comment by tuxor1337** [comment] 2015-02-18 21:28
I can't download from that page for testing. But I can tell you, that there is reasonable hope that it's possible to make this djvu work with document-viewer if it works with DjView, because both use the same library for parsing djvu (djvulibre). Maybe we just need to update to the most recent version of djvulibre - but this is a big "just", because my last attempt at updating djvulibre failed...

**Comment by tuxor1337** [comment] 2015-02-18 22:05
Okay, I was able to get access to the djvu file provided by that web page. The app renders this djvu just fine for me. So this doesn't seem to be an issue of document-viewer. Maybe something is wrong with your device/android version? Could you try yourself with a different android device or android rom?

**Comment by freeco** [comment] 2015-02-18 23:00
It may take several days.

**Comment by tuxor1337** [comment] 2015-03-17 20:51
Yes, everything fine about pages 20-25. If you can't give step by step instructions on how to reproduce I will have to close this.

**Comment by tuxor1337** [comment] 2015-04-16 23:32
Closing this since I'm unable to reproduce it.

**Closed by tuxor1337** 2015-04-16 23:32 UTC
Labels: unconfirmed
