### ISSUE TITLE
Sometimes 'Go to...' or 'Outline' doesn't work

### ISSUE THREAD

**Issue by FrankEular** [sufficientlysecure/document-viewer#48] opened 2014-06-01 04:38 UTC
It's a weird issue. Usually when I press 'Go to...' and type a number and press 'Go', it simply refreshes at the original page, not the page I inputted. I need to do twice or so to switch to a new page. The problem of 'Outline' is similar. When I choose a page in 'Outline', it stops at the original page. I need to do this many times to switch a page.

Android 4.1.2 (my Samsung phone) & Android 4.1.1 (my Samsung tab)
Document Viewer 2.5, installed from F-Droid.

**Comment by tuxor1337** [comment] 2015-01-29 09:53
Will be fixed, once mupdf is updated to the latest version. Use issue #51 to track the progress of the mupdf-update.

**Comment by tuxor1337** [comment] 2015-01-29 17:11
Just noticed, that this is still an issue. But it doesn't seem to be permanent?!

**Comment by FrankEular** [comment] 2015-05-16 14:33
I found that in the latest version, it sometimes went to the wrong page
when clicking outline, but it's a minor bug since the offset is always
plus/minus 1.

**Comment by tuxor1337** [comment] 2015-05-17 13:37
@FrankEular I'm using this app on a daily basis and haven't had any such issues for a long time now. Can you explain how to reproduce this step by step?

**Comment by FrankEular** [comment] 2015-06-21 16:42
Simply go through the outline and choose Chapter 1.
Maybe the problem is that the page of the chapter is DIFFERENT from
that of the first section of that chapter, just like:

Outline:

Chapter 1 <- page 8
1.1 xxx <- page 9

Click Chapter 1 then Document Viewer goes to page 9.

Sorry, the pdf file is too large to upload! Maybe I've pointed out the issue.

**Comment by tuxor1337** [comment] 2015-06-21 16:49
As long as there's only a single pdf that has this issue, I would suspect that the error lies in the pdf instead of this app. Have you compared with the behaviour of another pdf viewer? I won't reopen, as long as I'm not able to reproduce this.

**Comment by FrankEular** [comment] 2015-06-23 07:00
I opened it on my laptop with evince under linux, there was no problem.

The pdf file could be downloaded here:
http://gen.lib.rus.ec/book/index.php?md5=D9D636FAC19541905640F56164C8DA8A

Check "Chapter 1" in outline, say.

CAUTION: It's a pirate, therefore should be used with restriction.

**Comment by tuxor1337** [comment] 2015-06-23 09:47
That is indeed document specific. I don't know, why the problem doesn't occur in evince, because the outline seems to contain strange offsetY-values. Either the document's outline is broken and evince is able to ignore the problem or there's an error in MuPdf's outline handling.

**Comment by tuxor1337** [comment] 2015-06-23 11:00
The question is: what exactly is happening in `normalizeLinkTargetRect` what is the meaning of the flag `0x0F` in line 61 of `MuPdfDocument.java`? Why is this flag set in the outline of the above pdf, but not in other pdfs with similar outline?

**Comment by tuxor1337** [comment] 2015-06-23 11:12
The flags are all in mupdf's `include/mupdf/fitz/link.h` and apparently, with `0x0F` we check for `fz_link_flag_t_valid`, `fz_link_flag_l_valid`, `fz_link_flag_r_valid`, `fz_link_flag_b_valid` even though we only handle the `t` and `l` values. Solution: Only check for `0x03`. I think we can stick to ignoring the `b` and `r` parts because other pdf viewers do the same and noone seems to complain about that...

**Closed** 2015-06-23 11:18 UTC
Labels: bug
