### ISSUE TITLE
PDF cut off after page 276

### ISSUE THREAD

**Issue by dejj** [SufficientlySecure/document-viewer#176] opened 2016-03-14 14:12 UTC
I have a document of 312 pages, but document-viewer only shows 276. The document contains only plain text; the cut is in at an unremarkable position. I recompiled the document, leaving out some text in front. Some missing content then appears at the end, but the page number can not be greater than 276.
Version is 2.7.4.

**Comment by ericwa** [comment] 2016-03-14 18:11
This is probably this bug: https://github.com/SufficientlySecure/document-viewer/issues/136
I'll try to fix it before the next release!
As a workaround, renaming the file to a name that hasn't been used before should force DV to recalculate the number of pages.
Another workaround that might work:
 - long press on the book in the bookshelf/library view
 - "Clear recent data..."
 - "Clear cached data"

**Comment by dejj** [comment] 2016-03-15 09:47
Your suggestion to "Clear cached data" worked.
I remember adjusting pagebreaks, thereby increasing the document length after opening the PDF the first time. Therefore I assume that this is bug #136.
Thank you

**Comment by ericwa** [comment] 2016-06-03 22:48
I'll close this since it's a duplicate of https://github.com/SufficientlySecure/document-viewer/issues/136
(sorry, no fix yet 😞  )

**Closed by ericwa** 2016-06-03 22:48 UTC
